package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.Record;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    Record selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int updateByPrimaryKey(Record record);
}