package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.Record;
import com.thoughtCoding.theMall.vo.Statistics;

import java.util.List;
import java.util.Map;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    Record selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated Mon Jul 29 19:45:41 CST 2019
     */
    int updateByPrimaryKey(Record record);

    /**
     * 按月统计某年(某物)的销量
     */
    List<Statistics> selectCountByMonth(Map<String, String> map);

    /**
     * 得到(某物品)某一月按日统计的出货量
     */
    List<Statistics> selectCountByDay(Map<String, String> selectMap);

    /**
     * 得到(某类型物品)近一年按年龄划分的出货量
     */
    List<Statistics> selectCountByAge(String recordType);

    /**
     * 得到对应顾客id的历史购买记录
     */
    List<Record> selectRecordsByCustomerId(Integer customerId);
}