package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.Shop;

import java.util.List;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int deleteByPrimaryKey(Byte shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    Shop selectByPrimaryKey(Byte shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int updateByPrimaryKey(Shop record);

    /**
     * 根据店铺名查询shop
     */
    Shop selectShopByShopName(String shopName);

    /**
     * 查询全部店铺信息列表
     */
    List<Shop> selectAllShops();

}