package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.Statistics;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    int deleteByPrimaryKey(Short staId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    Statistics selectByPrimaryKey(Short staId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    int updateByPrimaryKeySelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    int updateByPrimaryKey(Statistics record);
}