package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.Suspicious;

public interface SuspiciousMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int deleteByPrimaryKey(Short susId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int insert(Suspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int insertSelective(Suspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    Suspicious selectByPrimaryKey(Short susId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int updateByPrimaryKeySelective(Suspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_suspicious
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    int updateByPrimaryKey(Suspicious record);
}