package com.thoughtCoding.theMall.mapper;

import com.thoughtCoding.theMall.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    int deleteByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    User selectByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 29 16:54:03 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 通过用户名和密码查询user
     */
    User selectUserByUsernameAndPassword(String username, String password);

    /**
     * 根据username查询user
     * @param username
     * @return
     */
    User selectUserByUsername(String username);
}