package com.thoughtCoding.theMall.model;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_sex
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte customerSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_age
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte customerAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_face_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private String customerFaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_is_black
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte customerIsBlack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_last_time
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Date customerLastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_id
     *
     * @return the value of t_customer.customer_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_id
     *
     * @param customerId the value for t_customer.customer_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_sex
     *
     * @return the value of t_customer.customer_sex
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_sex
     *
     * @param customerSex the value for t_customer.customer_sex
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerSex(Byte customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_age
     *
     * @return the value of t_customer.customer_age
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getCustomerAge() {
        return customerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_age
     *
     * @param customerAge the value for t_customer.customer_age
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerAge(Byte customerAge) {
        this.customerAge = customerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_face_id
     *
     * @return the value of t_customer.customer_face_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public String getCustomerFaceId() {
        return customerFaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_face_id
     *
     * @param customerFaceId the value for t_customer.customer_face_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerFaceId(String customerFaceId) {
        this.customerFaceId = customerFaceId == null ? null : customerFaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_type
     *
     * @return the value of t_customer.customer_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_type
     *
     * @param customerType the value for t_customer.customer_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerType(Byte customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_is_black
     *
     * @return the value of t_customer.customer_is_black
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getCustomerIsBlack() {
        return customerIsBlack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_is_black
     *
     * @param customerIsBlack the value for t_customer.customer_is_black
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerIsBlack(Byte customerIsBlack) {
        this.customerIsBlack = customerIsBlack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_last_time
     *
     * @return the value of t_customer.customer_last_time
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Date getCustomerLastTime() {
        return customerLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_last_time
     *
     * @param customerLastTime the value for t_customer.customer_last_time
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setCustomerLastTime(Date customerLastTime) {
        this.customerLastTime = customerLastTime;
    }
}