package com.thoughtCoding.theMall.model;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.shop_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    private Byte shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.shop_name
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    private String shopName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.shop_id
     *
     * @return the value of t_shop.shop_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public Byte getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.shop_id
     *
     * @param shopId the value for t_shop.shop_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public void setShopId(Byte shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.shop_name
     *
     * @return the value of t_shop.shop_name
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.shop_name
     *
     * @param shopName the value for t_shop.shop_name
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }
}