package com.thoughtCoding.theMall.model;

import java.util.Date;

public class Statistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.sta_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Short staId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.sta_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private String staType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.sta_date
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Date staDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.sta_sum
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Short staSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.sta_id
     *
     * @return the value of t_statistics.sta_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Short getStaId() {
        return staId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.sta_id
     *
     * @param staId the value for t_statistics.sta_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setStaId(Short staId) {
        this.staId = staId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.shop_id
     *
     * @return the value of t_statistics.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.shop_id
     *
     * @param shopId the value for t_statistics.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setShopId(Byte shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.sta_type
     *
     * @return the value of t_statistics.sta_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public String getStaType() {
        return staType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.sta_type
     *
     * @param staType the value for t_statistics.sta_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setStaType(String staType) {
        this.staType = staType == null ? null : staType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.sta_date
     *
     * @return the value of t_statistics.sta_date
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Date getStaDate() {
        return staDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.sta_date
     *
     * @param staDate the value for t_statistics.sta_date
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setStaDate(Date staDate) {
        this.staDate = staDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.sta_sum
     *
     * @return the value of t_statistics.sta_sum
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Short getStaSum() {
        return staSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.sta_sum
     *
     * @param staSum the value for t_statistics.sta_sum
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setStaSum(Short staSum) {
        this.staSum = staSum;
    }
}