package com.thoughtCoding.theMall.model;

import java.util.Date;

public class Suspicious {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_suspicious.sus_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    private Short susId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_suspicious.customer_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_suspicious.sus_datatime
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    private Date susDatatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_suspicious.sus_id
     *
     * @return the value of t_suspicious.sus_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public Short getSusId() {
        return susId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_suspicious.sus_id
     *
     * @param susId the value for t_suspicious.sus_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public void setSusId(Short susId) {
        this.susId = susId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_suspicious.customer_id
     *
     * @return the value of t_suspicious.customer_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_suspicious.customer_id
     *
     * @param customerId the value for t_suspicious.customer_id
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_suspicious.sus_datatime
     *
     * @return the value of t_suspicious.sus_datatime
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public Date getSusDatatime() {
        return susDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_suspicious.sus_datatime
     *
     * @param susDatatime the value for t_suspicious.sus_datatime
     *
     * @mbggenerated Mon Jul 29 14:59:23 CST 2019
     */
    public void setSusDatatime(Date susDatatime) {
        this.susDatatime = susDatatime;
    }
}