package com.thoughtCoding.theMall.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Short userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Byte shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    private Boolean userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Short getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setUserId(Short userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.shop_id
     *
     * @return the value of t_user.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Byte getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.shop_id
     *
     * @param shopId the value for t_user.shop_id
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setShopId(Byte shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_type
     *
     * @return the value of t_user.user_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_type
     *
     * @param userType the value for t_user.user_type
     *
     * @mbggenerated Mon Jul 29 16:13:19 CST 2019
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }
}