package com.thoughtCoding.alarm.mapper;

import com.thoughtCoding.alarm.model.Contact;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int deleteByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    Contact selectByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int updateByPrimaryKey(Contact record);
}