package com.thoughtCoding.alarm.mapper;

import com.thoughtCoding.alarm.model.Contact;

import java.util.List;
import java.util.Map;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int deleteByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    Contact selectByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Thu Oct 17 17:21:00 CST 2019
     */
    int updateByPrimaryKey(Contact record);

    /**
     * 找到对应用户所添加的所有紧急联系人
     * @param uid 用户的uid
     * @return 找到的紧急联系人列表
     */
    List<Contact> selectByUid(Short uid);

    /**
     * 删除uid对应用户的某个紧急联系人
     * @param paraMap {"uid":"要操作用户的uid", "callPhone":"要删除的紧急联系人手机号"}
     * @return 变更的信息数
     */
    int deleteByUidAndCallPhone(Map<String, Object> paraMap);
}